name: Build and Test

# See https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # build-and-test-unixy:
  #   name: Build and Test Web and Electron Apps on Linnux and MacOS
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest]
  #     fail-fast: false

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2.3.4

  #     - name: Install Node.js
  #       uses: actions/setup-node@v2.2.0
  #       with:
  #         node-version: 12
  #         cache: npm

  #     - name: Upgrade NPM
  #       run: npm install -g npm@7

  #     - name: Show Environment Info
  #       run: npm -v
      
  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Build web app
  #       run: npx gulp build --platform=browser
      
  #     - name: Test web app
  #       run: npm run do scripts/test

  #     - name: Build Electron app
  #       run: npm run do src/electron/build
  build-and-test-windows:
    name: Build and Test Web and Electron Apps on Windows
    runs-on: ubuntu-latest
    container: electronuserland/builder:wine
    steps:
      - name : checkout
        uses : "actions/checkout@v1"

      - name: Install Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14
          # cache: npm

      - name: Upgrade NPM
        run: npm install -g npm@7

      - name: Show Environment Info
        run: npm -v

      - name: Fix access bug
        run: apt update && apt install sudo && sudo chown -R 1001:121 "/github/home/.npm"
      
      - name: Install dependencies
        run: npm ci
      - name : build Windows Client
        with : { 
          entrypoint : "/bin/bash" , 
          args : '-c "cd $GITHUB_WORKSPACE && apt update && apt install -y rsync && npm run do src/electron/package_windows"' }
        uses : "docker://electronuserland/builder:wine"

