name: Build and Test

# See https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Install Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14
          cache: npm

      - name: Upgrade NPM
        run: npm install -g npm@7

      - name: Show Environment Info
        run: npm -v

      - name: Install dependencies
        run: npm ci

      - name: Build web app
        run: npx gulp build --platform=browser

      - name: Test web app
        run: npm run do scripts/test

      - name: Build Electron app
        run: npm run do src/electron/package_linux

  windows:
    name: Windows (Wine)
    # When updating Ubuntu versions, you will need to update the Wine APT commands.  See below.
    runs-on: ubuntu-20.04
    steps:
      - name : checkout
        uses : "actions/checkout@v1"

      - name: Install Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14
          cache: npm

      - name: Upgrade NPM
        run: npm install -g npm@7

      - name: Show Environment Info
        run: npm -v

      - name: Install dependencies
        run: npm ci

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          wget -nc https://dl.winehq.org/wine-builds/winehq.key
          sudo apt-key add winehq.key
          # This APT repo is specific to ubuntu 20.04. See https://wiki.winehq.org/Ubuntu when updating Ubuntu versions
          sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
          sudo apt update && sudo apt install --install-recommends winehq-stable\

      - name: Build Windows Client
        run: npm run do src/electron/package_windows

  mac:
    name: Apple
    runs-on: macos-10.15
    steps:
      - name : checkout
        uses : "actions/checkout@v1"

      - name: Install Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14
          cache: npm

      - name: Upgrade NPM
        run: npm install -g npm@7

      - name: Show Environment Info
        run: npm -v

      - name: Install dependencies
        run: npm ci

      - name: Print Build Settings
        run: |
          cd apple/xcode/osx
          xcodebuild -project Outline.xcodeproj -showBuildSettings

      - name: Build OSX Client
        run: npx gulp build --platform=osx
        if: ${{ false }} # See https://github.com/apache/cordova-osx/issues/104

      - name: Build iOS Client
        run: npx gulp build --platform=ios

  android:
    name: Android
    runs-on: ubuntu-20.04
    steps:
      - name : checkout
        uses : "actions/checkout@v1"

      - name: Set up Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Install Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14
          cache: npm

      - name: Upgrade NPM
        run: npm install -g npm@7

      - name: Show Environment Info
        run: npm -v

      - name: Install dependencies
        run: npm ci

      - name: Build Android Client
        run: npx gulp build --platform=android
