name: Build and Test

# See https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # build-and-test-unixy:
  #   name: Build and Test Web and Electron Apps on Linnux and MacOS
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest]
  #     fail-fast: false

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2.3.4

  #     - name: Install Node.js
  #       uses: actions/setup-node@v2.2.0
  #       with:
  #         node-version: 12
  #         cache: npm

  #     - name: Upgrade NPM
  #       run: npm install -g npm@7

  #     - name: Show Environment Info
  #       run: npm -v
      
  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Build web app
  #       run: npx gulp build --platform=browser
      
  #     - name: Test web app
  #       run: npm run do scripts/test

  #     - name: Build Electron app
  #       run: npm run do src/electron/build
  build-and-test-windows:
    name: Build and Test Web and Electron Apps on Windows
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses : "actions/checkout@v1"

      - name: Install Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14
          # cache: npm

      - name: Upgrade NPM
        run: npm install -g npm@7

      - name: Show Environment Info
        run: npm -v
      
      - name: Install dependencies
        run: npm ci

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386 
          wget -nc https://dl.winehq.org/wine-builds/winehq.key
          apt update && apt install sudo && sudo apt-key add winehq.key
          sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
          sudo apt update && sudo apt install --install-recommends winehq-stable
      - name: Build Windows Client
        run: npm run do src/electron/package_windows

