name: Build and Test

# See https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm
      
      - name: Install Dependencies
        run: npm ci

      - name: Build Web App
        run: npx gulp build --platform=browser

      - name: Test Web App
        run: npm run action scripts/test

      - name: Build Electron App
        run: npm run action src/electron/package_linux

  windows:
    name: Windows
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Windows Client
        run: npm run action src/electron/package_windows

  mac:
    name: Apple
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Set XCode Version
        run: sudo xcode-select -switch /Applications/Xcode_12.5.app

      - name: Build OSX Client
        run: npx gulp build --platform=osx

      - name: Build iOS Client
        run: npm run action apple/scripts/ios_package_remote

  android:
    name: Android
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Set Android SDK Version
        run: sdkmanager "platform;android-29"

      - name: Build Android Client
        run: npx gulp build --platform=android
