name: Build Release Candidates

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
  apple:
    name: Build Apple Release Candidates
    runs-on: macos-11
    timeout-minutes: 15
    environment: Client Apple Release
    env:
      APPLE_CREDENTIALS_DEPLOY_KEY: ${{ secrets.APPLE_CREDENTIALS_DEPLOY_KEY }}
      APPLE_CREDENTIALS_REPOSITORY: ${{ secrets.APPLE_CREDENTIALS_REPOSITORY }}
      APPLE_DEV_PORTAL_TEAM_ID: ${{ secrets.APPLE_DEV_PORTAL_TEAM_ID }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ITUNES_CONNECT_ID: ${{ secrets.APPLE_ITUNES_CONNECT_ID }}
      MATCH_PASSWORD: ${{ secrets.APPLE_MATCH_PASSWORD }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Set XCode Version
        run: sudo xcode-select -switch /Applications/Xcode_13.2.app

      - name: Build Apple Clients
        run: |
          npm run action apple/build ios -- --buildMode=release
          npm run action apple/build osx -- --buildMode=release

      - name: Upload iOS Client
        uses: actions/upload-artifact@v2
        with:
          name: client_ios_release_${{ github.sha }}
          path: platforms/ios/Outline.ipa
          if-no-files-found: error

      - name: Upload OSX Client
        uses: actions/upload-artifact@v2
        with:
          name: client_osx_release_${{ github.sha }}
          path: platforms/osx/Outline.app
          if-no-files-found: error

  linux:
    name: Build Linux Release Candidate
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Linux Release Candidate
        run: npm run action src/electron/build linux -- --buildMode=release

      - name: Upload Linux Release Candidate
        uses: actions/upload-artifact@v2
        with:
          name: client_linux_release_${{ github.sha }}
          path: build/dist
          if-no-files-found: error
