name: Build Release Candidates

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: Linux Release Candidate
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      INFO_FILE_CHANNEL: beta
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Linux Release Candidate
        run: npm run action src/electron/release_linux

      - name: Upload Linux Release Candidate
        uses: actions/upload-artifact@v2
        with:
          name: linux-${{ env.GITHUB_REF }}
          path: |
            build/dist/Outline-Client.AppImage
            build/dist/linux-beta.yml
          if-no-files-found: error
