name: Linux Prerelease

on: 
  workflow_dispatch:
    inputs:
      version_number:
        description: "Version of Linux Client to Prerelease"
        required: true

jobs:
  create_prerelease:
    name: Create Linux Prerelease
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    env:
      PRERELEASE_VERSION: ${{ github.event.inputs.version_number }}
      PRERELEASE_TAG: linux-v${{ github.event.inputs.version_number }}
      CI_TAG: linux-v${{ github.event.inputs.version_number }}

    steps:
      - name: Validate Input
        run: |
          [[ "${PRERELEASE_VERSION}" =~ /^[0-9]+\.[0-9]+\.[0-9]+$/ ]] || exit 1

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Validate Version
        run: |
          MOST_RECENT_TAG="$(git tag -l "linux-v*" | tail -n1)"

          # confirm given tag version is greater than the most recent
          [[ $MOST_RECENT_TAG == $PRERELEASE_TAG ]] && exit 1
          [[ "$(sort -V $MOST_RECENT_TAG $PRERELEASE_TAG | tail -n1)" == "${PRERELEASE_TAG}" ]] || exit 1

      - name: Tag Prerelease
        run: |
          git tag -a "${PRERELEASE_TAG}"
          git push origin "${PRERELEASE_TAG}"

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Production Linux Client
        run: npm run action src/electron/release_linux

      - name: Create Prerelease
        uses: actions/create-release@v1
        id: create_prerelease
        with:
          tag_name: ${{ env.PRERELEASE_TAG }}
          release_name: Linux Client v${{ env.PRERELEASE_VERSION }}
          prerelease: true

      - name: Upload Prerelease Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_prerelease.outputs.upload_url }}
          asset_content_type: application/zip
          asset_path: # TODO
          asset_name: # TODO

