name: Linux Prerelease

on: 
  workflow_dispatch:
    inputs:
      version_number:
        description: "Version of Linux Client to Prerelease"
        required: true

jobs:
  create_prerelease:
    name: Create Linux Prerelease
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    environment: Prerelease / Linux
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Create Release Candidate Tag
        run: echo "PRERELEASE_TAG=$(bash ./scripts/semantic_version.sh ${{ github.event.inputs.version_number }} linux prerelease)" >> $GITHUB_ENV

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: npm ci

      - name: Tag Release Candidate
        run: |
          git config --global user.name "OutlineBot"
          git config --global user.email "bot@getoutline.org" # TODO
          git tag ${{ env.PRERELEASE_TAG }}

      - name: Build Release Candidate Linux Client
        run: npm run action src/electron/prerelease_linux ${{ github.event.inputs.version_number }}
      
      - name: Push Release Candidate Tag
        run: git push origin ${{ env.PRERELEASE_TAG }}

      - name: Create Prerelease
        uses: softprops/action-gh-release@v1
        id: prerelease
        with:
          name: "Linux Client v${{ github.event.inputs.version_number }}"
          tag_name: ${{ env.PRERELEASE_TAG }}
          prerelease: true
          files: |
            build/dist/Outline-Client.AppImage
            build/dist/beta-linux.yml
