name: Linux Prerelease

on: 
  workflow_dispatch:
    inputs:
      version_number:
        description: "Version of Linux Client to Prerelease"
        required: true

jobs:
  create_prerelease:
    name: Create Linux Prerelease
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    environment: Production / Linux
    env:
      PRERELEASE_VERSION: ${{ github.event.inputs.version_number }}
      PRERELEASE_TAG: linux-v${{ github.event.inputs.version_number }}
      CI_TAG: linux-v${{ github.event.inputs.version_number }}
      RELEASE_BRANCH: linux-client-v${{ github.event.inputs.version_number }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Validate Input
        run: |
          [[ "${PRERELEASE_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit 1

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Validate Version
        run: |
          MOST_RECENT_TAG="$(git tag -l "linux-v*" | tail -n1)"

          # confirm given tag version is greater than the most recent
          [[ "${MOST_RECENT_TAG}" == "${PRERELEASE_TAG}" ]] && exit 1
          [[ "$(echo -e "${MOST_RECENT_TAG}\n${PRERELEASE_TAG}" | sort -V | tail -n1)" == "${PRERELEASE_TAG}" ]] || exit 1

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: npm ci

      - name: Tag Prerelease
        run: |
          git config --global user.name "OutlineBot"
          git config --global user.email "bot@getoutline.org" # TODO
          git tag "${PRERELEASE_TAG}"

      - name: Build Production Linux Client
        run: npm run action src/electron/release_linux
      
      - name: Push Prerelease Tag
        run: git push origin "${PRERELEASE_TAG}"

      - name: Create Prerelease
        uses: softprops/action-gh-release@v1
        id: prerelease
        with:
          name: "Linux Client v${{ env.PRERELEASE_VERSION }}"
          tag_name: ${{ env.PRERELEASE_TAG }}
          prerelease: true
          files: |
            build/dist/Outline-Client.AppImage
            build/dist/latest-linux.yml
