name: Linux Prerelease

on: 
  workflow_dispatch:
    inputs:
      version_number:
        description: "Version of Linux Client to Prerelease"
        required: true

jobs:
  create_prerelease:
    name: Create Linux Prerelease
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    environment: Production / Linux
    env:
      PRERELEASE_VERSION: ${{ github.event.inputs.version_number }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Create Release Candidate Tag
        id: tags
        run: echo ::set-output name=prelease::"$(npm run action scripts/semantic_version linux "${{ env.PRELEASE_VERSION }})" prerelease)"

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: npm ci

      - name: Tag Release Candidate
        run: |
          git config --global user.name "OutlineBot"
          git config --global user.email "bot@getoutline.org" # TODO
          git tag ${{ steps.tags.outputs.prerelease }}

      - name: Build Release Candidate Linux Client
        run: npm run action src/electron/prerelease_linux ${{ steps.tags.outputs.prerelease }}
      
      - name: Push Release Candidate Tag
        run: git push origin ${{ steps.tags.outputs.prerelease }}

      - name: Create Prerelease
        uses: softprops/action-gh-release@v1
        id: prerelease
        with:
          name: "Linux Client v${{ env.PRERELEASE_VERSION }}"
          tag_name: ${{ steps.tags.outputs.prerelease }}
          prerelease: true
          files: |
            build/dist/Outline-Client.AppImage
            build/dist/latest-linux.yml
